### PR TITLE
* updated requirements in aws shell python package

### PR DESCRIPTION
**Pull request by alexazarh**
* changed AWSApi to AWSEC2Service
* fixed failing tests

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/aws-shell/80)

### CODE REVIEW

**Comment by razaba** [comment]
Reviewed 12 of 13 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[package/version.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/80#-KJdhbWfRV6tTnV2L771:-KJdhbWfRV6tTnV2L772:-870096369) ([raw file](https://github.com/qualisystems/aws-shell/blob/4a9c31b428589692471658cd7fd909a36a568ea0/package/version.txt#L1)):*
> ```
> 0.1.999999
> ```

please fix the version file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/80)*

**Comment by razaba** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/80)*

**Comment by alexazarh** [comment]
*[package/version.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/80#-KJdhbWfRV6tTnV2L771:-KJetByUDXhMKFDGLc3s:-499146009) ([raw file](https://github.com/qualisystems/aws-shell/blob/4a9c31b428589692471658cd7fd909a36a568ea0/package/version.txt#L1)):*
<details><summary><i>Previously, razaba (Raz Abadi) wrote…</i></summary>
> please fix the version file
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/80)*

**Comment by razaba** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/80)*

**Pull request merged**
