### PR TITLE
GetApplicationPorts - issue #70

### PR DESCRIPTION
**Pull request by alexazarh**
1. Added GetApplicationPorts command as a connected command
2. Refactored SG creation so it will not create a SG if the values of the inbound/outbound attributes are not valid
3. Fixed failing tests and add new tests

Not breaking

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/aws-shell/93)

### CODE REVIEW

**Comment by razaba** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drivers/aws_shell_driver/src/drivermetadata.xml, line 3 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHd-2nmPybyzqrLu34:-KKHd-2nmPybyzqrLu35:-2102662898) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/drivers/aws_shell_driver/src/drivermetadata.xml#L3)):*
> ```XML
> <Driver Description="This driver orchestrate all the command that will be executed on AWS" MainClass="driver.AWSShellDriver" Name="AWS Shell Driver" Version="0.1.9999999">
>     <Layout>
>         <Category Name="Deployment">
> ```

please fix the version and then run pack.bat before checking in

---

*[package/cloudshell/cp/aws/domain/deployed_app/operations/app_ports_operation.py, line 40 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHe-Ps5KRwUSk2ymCT:-KKHe-Ps5KRwUSk2ymCU:-144431683) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/cloudshell/cp/aws/domain/deployed_app/operations/app_ports_operation.py#L40)):*
> ```Python
> 
>     def _get_custom_param_value(self, custom_params, name):
>         name = name.lower()
> ```

shouldn't it be in a domain service?
VMCusotomParamService? 

---

*[package/tests/test_deployed_app/__init__.py, line 0 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHhKqNyQwpyKjbsJzH:-KKHhKqNyQwpyKjbsJzI:-386904136) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/tests/test_deployed_app/__init__.py#L0)):*
do we need to add author?

---

*[package/tests/test_deployed_app/test_operations/__init__.py, line 0 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHhYo_7VI-auCe2l8B:-KKHhYo_7VI-auCe2l8C:-386904136) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/tests/test_deployed_app/test_operations/__init__.py#L0)):*
do we need to add author?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by alexazarh** [comment]
*[package/tests/test_deployed_app/__init__.py, line  \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHhKqNyQwpyKjbsJzH:-KKICqt3zcRLWJ38UrAg:-1980065087) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/tests/test_deployed_app/__init__.py#L)):*
<details><summary><i>Previously, razaba (Raz Abadi) wrote…</i></summary>
> do we need to add author?
</details>
no because its in the testing part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by razaba** [comment]
Reviewed 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by razaba** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by razaba** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-:-KKIIrYRWHxRdnaoxw65:1417088721)*

**Comment by razaba** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by alexazarh** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package/cloudshell/cp/aws/domain/deployed_app/operations/app_ports_operation.py, line 40 \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHe-Ps5KRwUSk2ymCT:-KKIJT5jwY8fJItx25cF:-499146009) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/cloudshell/cp/aws/domain/deployed_app/operations/app_ports_operation.py#L40)):*
<details><summary><i>Previously, razaba (Raz Abadi) wrote…</i></summary>
> shouldn't it be in a domain service?
> VMCusotomParamService? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Comment by alexazarh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package/tests/test_deployed_app/test_operations/__init__.py, line  \[r1\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/93#-KKHhYo_7VI-auCe2l8B:-KKIJXGmJAhUxDLshLd1:-499146009) ([raw file](https://github.com/qualisystems/aws-shell/blob/1f2aff9e7eac3cc3a3fd1945236cbac9ab983a6b/package/tests/test_deployed_app/test_operations/__init__.py#L)):*
<details><summary><i>Previously, razaba (Raz Abadi) wrote…</i></summary>
> do we need to add author?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/93)*

**Pull request merged**
