### PR TITLE
Get credentials for a Windows Instance at the deployment #5

### PR DESCRIPTION
**Pull request by razaba**
#5 

adding a windows credentials provider and adding it at the deployment

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/aws-shell/95)

### CODE REVIEW

**Comment by alexazarh** [comment]
*[package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py, line 14 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIrULtcuzV3cktB0gc:-KKIrULtcuzV3cktB0gd:1765850397) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py#L14)):*
> ```Python
> 
>     def get_windows_credentials(self, instance, key_value, wait_for_password=True):
>         password_data = instance.password_data()['PasswordData']
> ```

add doc string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by alexazarh** [comment]
Review status: 0 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[package/requirements.txt, line 6 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIpNyLCaW7PPEygCoy:-KKIpNyMz9N-kMFY8WKD:-526246033) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/requirements.txt#L6)):*
> ```
> jsonpickle==0.9.3
> enum==0.4.6
> pycrypto
> ```

set explicit version

---

*[package/version.txt, line 1 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIpQnlCxCJAWaJCD6l:-KKIpQnlCxCJAWaJCD6m:526012598) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/version.txt#L1)):*
> ```
> 0.1.999999
> ```

fix versrion

---

*[package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py, line 58 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIpfoZyTwSasYHZF7q:-KKIpfoZyTwSasYHZF7r:1572931717) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py#L58)):*
> ```Python
>                                                     ami_deployment_model.wait_for_credentials,
>                                                     result)
> ```

call method with named params

---

*[package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py, line 87 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIr6sHSv-fwiKQttdE:-KKIr6sHSv-fwiKQttdF:858455894) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py#L87)):*
> ```Python
> 
>         # returns the key for linux usage
>         return {'Private Key': key_value}
> ```

remove this line - not needed

---

*[package/cloudshell/cp/aws/domain/services/ami_credentials_service/__init__.py, line 0 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIrFo3VbEUK5bt0TPH:-KKIrFo3VbEUK5bt0TPI:-2100430033) ([raw file](https://github.com/qualisystems/aws-shell/blob/3a7f044ea58368bec0550d52ba279d6659e29391/package/cloudshell/cp/aws/domain/services/ami_credentials_service/__init__.py#L0)):*
add author like other init files

---

*[package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py, line 72 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIruK9Lyo0Gx0LxrgY:-KKIruK9Lyo0Gx0LxrgZ:-1052669339) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py#L72)):*
> ```Python
>     def __init__(self, user_name, password):
>         self.user_name = user_name
>         self.password = password
> ```

move to models

---

*[package/cloudshell/cp/aws/domain/services/task_manager/password_waiter.py, line 5 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIspKfOrYZ-vstDMSs:-KKIspKfOrYZ-vstDMSt:-1112463219) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/services/task_manager/password_waiter.py#L5)):*
> ```Python
> 
> class PasswordWaiter(object):
>     def __init__(self, delay=2, timeout=10):
> ```

change delay to 10 sec

---

*[package/cloudshell/cp/aws/domain/services/task_manager/password_waiter.py, line 15 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIsLzVXq_i0pZvUC7W:-KKIsLzVXq_i0pZvUC7X:1765850397) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/services/task_manager/password_waiter.py#L15)):*
> ```Python
>         self.timeout = timeout * 60
> 
>     def wait(self, instance):
> ```

add doc string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by razaba** [comment]
Review status: 0 of 21 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py, line 72 \[r2\]](https://reviewable.io:443/reviews/qualisystems/aws-shell/95#-KKIruK9Lyo0Gx0LxrgY:-KKIvS47hXRvDbtYp619:-499146009) ([raw file](https://github.com/qualisystems/aws-shell/blob/001e929e2aa7be93f074d086fe031bf91840f293/package/cloudshell/cp/aws/domain/services/ami_credentials_service/ami_credentials_service.py#L72)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary>
> move to models
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by alexazarh** [comment]
Reviewed 10 of 19 files at r1, 4 of 7 files at r2, 7 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by alexazarh** [comment]
Reviewed 1 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by alexazarh** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by razaba** [comment]
Reviewed 2 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Comment by razaba** [comment]
Reviewed 9 of 19 files at r1, 4 of 7 files at r2, 6 of 8 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/aws-shell/95)*

**Pull request merged**
